services:
  - type: web
    name: msprodata
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: msprodata-db
          property: internalConnectionString