services:
  - type: web
    name: msprodata
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: "ls -la"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msprodata-db
          property: connectionString
      - key: FLASK_APP
        value: "wsgi:app"
      - key: SECRET_KEY
        generateValue: true
