services:
  - type: web
    name: msprodata
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msprodata-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
    # Set the startup command for the application
    startCommand: "flask db upgrade && gunicorn --bind 0.0.0.0:${PORT} wsgi:app"
    # The initialDeployHook will now handle the full migration setup
    initialDeployHook: "flask db init && flask db migrate -m 'Initial migration' && flask db upgrade"
