services:
  - type: web
    name: msprodata
    # We are now using the 'docker' environment instead of 'python'
    env: docker
    region: singapore
    plan: free
    branch: main
    # The 'dockerfilePath' points to our newly created Dockerfile
    dockerfilePath: ./Dockerfile
    # We can now use the standard command as the new base image has a proper PATH.
    dockerCommand: "python -m gunicorn --bind 0.0.0.0:10000 wsgi:app"
    # We still need the database connection string
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msprodata-db
          property: connectionString