services:
  - type: web
    name: msprodata
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msprodata-db
          property: connectionString
      - key: FLASK_APP
        value: "app.py"
    # The build command will now directly run the database upgrade
    buildCommand: "flask db upgrade"
    # The start command is only responsible for starting the server
    startCommand: "gunicorn --bind 0.0.0.0:${PORT} wsgi:app"
