services:
  - type: web
    name: msprodata
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msprodata-db
          property: connectionString
      - key: FLASK_APP
        value: "app.py"
    # The build command (if needed) can go here.
    # The start command will now run migrations and then start the server.
    startCommand: "flask db upgrade && gunicorn --bind 0.0.0.0:${PORT} wsgi:app"
